- gradle/configure.gradle
Improve Gradle configuration script - do not fail if config files are not present in .gradle dir
> Improve gradle configuration script

- .github/workflows/pull_request.yml
> Setup pull requests

- gradle/configure.gradle
Configuration parameters can be set via the command line. Example:
./gradlew configure -Pvsphere.url=https://vsphere.com
> Gradle configuration task: command line parameters

- build.gradle
- gradle/configure.gradle
- gradle/corfu.gradle
Gradle improvements: 
- idea settings - download JavaDoc and sources, specify java lang level
- dependencies strategy - update snapshots each time
> Gradle improvements: idea settings, dependencies strategy

- gradle/idea.gradle
> gradle runner fix

- build.gradle
- gradle/idea.gradle
- gradle/java.gradle
Gradle test: don't print stacktrace
> Gradle test: don't print stacktrace

- gradle/wrapper/gradle-wrapper.properties
- tests/build.gradle
Migrate to Gradle 6.1.1
Update protobuf plugin
> Migrate to Gradle 6.1.1

- .ci/bat_tests.sh
- gradle/java.gradle
- tests/src/main/java/org/corfudb/universe/test/util/ScenarioUtils.java
- tests/src/test/java/org/corfudb/test/vm/stateful/ufo/NodeDownAndLinkFailureTest.java
Fix NodeDownAndLinkFailureTest
> Fix bat tests: NodeDownAndLinkFailureTest

- gradle/corfu.gradle
Provide information about Corfu infrastructure jar that is used
> Provide information about corfu infrastructure jar that is used

- gradle/corfu.gradle
> Provide information about corfu infrastructure that is used. Fix

- gradle/java.gradle
Generate Junit test/xml reports in build/test-results directory
> Enabling Junit xml report

- .ci/bat_tests.sh
- benchmarks/src/jmh/java/org/corfudb/benchmarks/cluster/ClusterBenchmark.java
- tests/src/main/java/org/corfudb/universe/test/UniverseConfigurator.java
Collecting logs from corfu cluster
> Collecting logs from corfu cluster

- tests/src/test/java/org/corfudb/test/vm/stateful/ufo/NodeUpAndPartitionedTest.java
Changes:
* Added further checks to make sure layout is received with the correct stripe servers and unresponsive nodes.
> Fixing NodeUpAndPartitionedTest by removing the Cluster unavailable exception by following change(s):

- cloud/infrastructure/logstash/logstash/configuration/pipeline/corfu-jvm.conf
- cloud/infrastructure/logstash/logstash/configuration/pipeline/corfu.conf
- cloud/infrastructure/logstash/logstash/manager/config/logstash.yml
- cloud/infrastructure/logstash/logstash/manager/pipeline/logstash.conf
Logstash-manager project, fixes
> Logstash-manager project, fixes

- cloud/infrastructure/kibana/kibana-tools/build.gradle.kts
- cloud/infrastructure/logstash/logstash/configuration/pipeline/corfu.conf
- cloud/infrastructure/logstash/logstash/manager/pipeline/logstash.conf
> Logstash-manager fixes

- cloud/infrastructure/filebeat/filebeat/Dockerfile
- cloud/infrastructure/filebeat/filebeat/docker-compose.yml
- cloud/infrastructure/filebeat/filebeat/filebeat.yml
- cloud/infrastructure/filebeat/filebeat/inputs.d/corfu.yml
- cloud/infrastructure/logstash/logstash-tools/build.gradle.kts
- settings.gradle
Creating filebeat infrastructure project
> filebeat infrastructure

- cloud/infrastructure/integration-tools/build.gradle.kts
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/Main.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/server/Server.kt
- cloud/infrastructure/integration-tools/src/main/resources/application.conf
- cloud/infrastructure/integration-tools/src/main/resources/logback.xml
Implement integration-server very basic version
> Implement integration-server very basic version

- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/Json.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/Main.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/extractor/DownloadCommand.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/extractor/UnpackCommand.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/kibana/DashboardCommand.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/loader/LoaderCommand.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/processing/ProcessingCommand.kt
- cloud/infrastructure/kibana/kibana-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/kibana/tools/Main.kt
Integration-tools: bring kibana dashboards deployment functionality
> Integration-tools: bring kibana dashboards deployment functionality

- cloud/infrastructure/integration-tools/Dockerfile
- cloud/infrastructure/integration-tools/integration-tool-runner.py
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/loader/LoaderCommand.kt
Detecting docker path in integration-tool-runner.py
> Detecting docker path in integration-tool-runner.py

- cloud/infrastructure/integration-tools/integration-tools-server.sh
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/kv/kvstore.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/server/Server.kt
- cloud/infrastructure/integration-tools/src/main/resources/logback.xml
- cloud/infrastructure/integration-tools/src/main/resources/static/script.js
- cloud/infrastructure/integration-tools/src/test/kotlin/org/corfudb/cloud/infrastructure/integration/processing/KvStoreTest.kt
Integration-tools server - kv column families fixes
> Integration-tools server - kv column families fixes

- cloud/infrastructure/integration-tools/integration-tools-server.sh
- cloud/infrastructure/integration-tools/src/main/resources/static/script.js
Integration-tools server - script.js improvements
> Integration-tools server - script.js improvements

- cloud/infrastructure/filebeat/filebeat/build.gradle.kts
- cloud/infrastructure/logstash/logstash/build.gradle.kts
- settings.gradle
Gradle -> docker-compose integration
> Gradle -> docker-compose integration

- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/extractor/DownloadCommand.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/extractor/UnpackCommand.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/kv/kvstore.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/loader/LoaderCommand.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/processing/ProcessingCommand.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/server/Server.kt
- cloud/infrastructure/integration-tools/src/main/resources/static/script.js
- cloud/infrastructure/integration-tools/src/test/kotlin/org/corfudb/cloud/infrastructure/integration/processing/KvStoreTest.kt
Integration server: handle exceptions and log them
> Integration server: handle exceptions and log them

- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/extractor/UnpackCommand.kt
- gradle.properties
> Unpack command - fixes

- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/extractor/CleanUp.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/processing/ProcessingCommand.kt
- cloud/infrastructure/logstash/logstash/docker-compose.yml
Disposable infrastructure improvements
> Disposable infrastructure improvements

- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/kv/kvstore.kt
- cloud/infrastructure/integration-tools/src/test/kotlin/org/corfudb/cloud/infrastructure/integration/processing/KvStoreTest.kt
- cloud/infrastructure/logstash/logstash/Dockerfile
Rocksdb initialization improvements
> Rocksdb initialization improvements

- cloud/infrastructure/integration-tools/src/main/resources/static/index.html
> BabelJs version fix

- cloud/infrastructure/docker-elk/apm-server-down.sh
- cloud/infrastructure/docker-elk/apm-server-up.sh
- cloud/infrastructure/logstash/logstash/docker-compose.yml
> Bring ELK APM server

- cloud/infrastructure/docker-elk/apm-server-down.sh
- cloud/infrastructure/docker-elk/apm-server-up.sh
> APM server command line fix

- cloud/infrastructure/logstash/logstash/configuration/pipeline/corfu-jvm.conf
Kibana jvm GC parser - parse float values
> Kibana jvm GC parser - parse float values

- cloud/infrastructure/kibana/dashboard/corfu-dashboard/basic.json
- cloud/infrastructure/kibana/dashboard/corfu-dashboard/checkpoint.json
- cloud/infrastructure/kibana/dashboard/corfu-dashboard/corfu-cluster-dashboard.json
- cloud/infrastructure/kibana/dashboard/corfu-dashboard/corfu.json
- cloud/infrastructure/logstash/logstash/configuration/patterns/gc
Kibana dashboards - migrate to 7.7.1 version (in configs)
> Kibana dashboards - migrate to 7.7.1 version (in configs)

- cloud/infrastructure/docker-elk/docker-compose.yml
- cloud/infrastructure/docker-elk/elk-down.sh
- cloud/infrastructure/docker-elk/init.sh
> Docker elk config parameters

- cloud/infrastructure/kibana/dashboard/index-pattern.json
Kibana index-pattern.json rollback migrationVersion
> Kibana index-pattern.json rollback migrationVersion

- cloud/infrastructure/kibana/dashboard/corfu-dashboard/basic.json
- cloud/infrastructure/kibana/dashboard/corfu-dashboard/checkpoint.json
- cloud/infrastructure/kibana/dashboard/corfu-dashboard/corfu-cluster-dashboard.json
- cloud/infrastructure/kibana/dashboard/corfu-dashboard/corfu.json
Rollback kibana dashboard versions to 7.6.0
> Rollback kibana dashboard versions to 7.6.0

- cloud/infrastructure/kibana/dashboard/corfu-dashboard/corf-gc-dashboard.json
> Bring corfu GC dashboard

- cloud/infrastructure/logstash/logstash-tools/src/test/java/org/corfu/cloud/infrastructure/logstash/CorfuTest.java
- cloud/infrastructure/logstash/logstash-tools/src/test/resources/corfu/input.log
- cloud/infrastructure/logstash/logstash-tools/src/test/resources/corfu/output.log
- cloud/infrastructure/logstash/logstash/configuration/pipeline/corfu.conf
Logstash Corfu - decrease noise
> Logstash corfu - decrease noise

- cloud/infrastructure/logstash/logstash/configuration/pipeline/corfu.conf
> Logstash corfu - decrease noise v2

- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/kv/kvstore.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/transform/Transform.kt
Integration-tools: transformation/data pre-processing step - add logs… and commands output
> Integration-tools: add logs

- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/Json.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/transform/Transform.kt
Pre processing - set working directory
> Pre processing - set working directory

- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/transform/Transform.kt
Integration tools - transform, add logs
> Integration tools - transform, add logs

- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/transform/Transform.kt
Integration tools - transform, add archives
> Integration tools - transform, add archives

- cloud/infrastructure/kibana/dashboard/corfu-dashboard/corfu-cluster-dashboard.json
Kibana, corfu-cluster-dashboard - add gc stats
> Kibana, corfu-cluster-dashboard - add gc stats

- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/extractor/DownloadCommand.kt
- cloud/infrastructure/integration-tools/src/main/kotlin/org/corfudb/cloud/infrastructure/integration/extractor/UnpackCommand.kt
- cloud/infrastructure/integration-tools/src/main/resources/logback.xml
Integration tools: prevent memory leaks
> Integration tools: prevent memory leaks

- gradle/java.gradle
- universe/src/main/java/org/corfudb/universe/node/server/docker/DockerCorfuServer.java
- universe/src/main/java/org/corfudb/universe/util/DockerManager.java
Universe Framework - implement the "execute" method in DockerCorfuServer
> Universe Framework - implement "execute" method in DockerCorfuServer

- universe/src/main/java/org/corfudb/universe/node/server/AbstractCorfuServer.java
- universe/src/main/java/org/corfudb/universe/node/server/CorfuServerParams.java
- universe/src/main/java/org/corfudb/universe/node/server/docker/DockerCorfuServer.java
- universe/src/main/java/org/corfudb/universe/node/server/process/ProcessCorfuServer.java
- universe/src/main/java/org/corfudb/universe/node/server/vm/VmCorfuServer.java
Universe framework - move Corfu cmd line into Corfu params
> Universe framework - move corfu cmd line into corfu params

- universe/src/main/java/org/corfudb/universe/api/node/Node.java
- universe/src/main/java/org/corfudb/universe/group/cluster/docker/DockerCorfuCluster.java
- universe/src/main/java/org/corfudb/universe/group/cluster/docker/DockerSupportCluster.java
- universe/src/main/java/org/corfudb/universe/node/client/ClientParams.java
- universe/src/main/java/org/corfudb/universe/node/server/CorfuServerParams.java
- universe/src/main/java/org/corfudb/universe/node/server/SupportServerParams.java
- universe/src/main/java/org/corfudb/universe/node/server/docker/DockerCorfuServer.java
- universe/src/main/java/org/corfudb/universe/node/server/docker/DockerSupportServer.java
- universe/src/main/java/org/corfudb/universe/util/DockerManager.java
DockerCorfuServer refactoring - make the server more generic
> DockerCorfuServer refactoring - make the server more generic

- .github/workflows/docker-publish.yml
GitHub actions add docker caching
> github actions add docker caching

- universe/src/main/java/org/corfudb/universe/infrastructure/docker/universe/DockerUniverse.java
- universe/src/main/java/org/corfudb/universe/infrastructure/docker/universe/group/cluster/DockerCorfuCluster.java
- universe/src/main/java/org/corfudb/universe/infrastructure/docker/universe/group/cluster/DockerPrometheusCluster.java
- universe/src/main/java/org/corfudb/universe/infrastructure/docker/universe/node/server/corfu/DockerCorfuServer.java
- universe/src/main/java/org/corfudb/universe/infrastructure/docker/universe/node/server/prometheus/DockerPrometheusServer.java
- universe/src/main/java/org/corfudb/universe/infrastructure/docker/universe/node/server/prometheus/PrometheusConfig.java
- universe/src/main/java/org/corfudb/universe/scenario/fixture/Fixtures.java
- universe/src/main/java/org/corfudb/universe/universe/node/server/prometheus/PromServerParams.java
- universe/src/main/java/org/corfudb/universe/universe/node/server/prometheus/PrometheusServerParams.java
universe framework v3 - reorganize server package structure
> universe framework v3 - reorganize server package structure

- universe/src/main/java/org/corfudb/universe/api/deployment/docker/DockerContainerParams.java
- universe/src/main/java/org/corfudb/universe/api/deployment/vm/VmParams.java
- universe/src/main/java/org/corfudb/universe/api/universe/group/GroupParams.java
- universe/src/main/java/org/corfudb/universe/api/universe/group/cluster/AbstractCluster.java
- universe/src/main/java/org/corfudb/universe/api/universe/node/Node.java
- universe/src/main/java/org/corfudb/universe/infrastructure/docker/universe/group/cluster/DockerCassandraCluster.java
- universe/src/main/java/org/corfudb/universe/infrastructure/docker/universe/node/server/cassandra/DockerCassandraServer.java
- universe/src/main/java/org/corfudb/universe/infrastructure/docker/universe/node/server/prometheus/DockerPrometheusServer.java
- universe/src/main/java/org/corfudb/universe/scenario/fixture/Fixtures.java
- universe/src/main/java/org/corfudb/universe/universe/group/cluster/corfu/AbstractCorfuCluster.java
- universe/src/main/java/org/corfudb/universe/universe/node/client/LocalCorfuClient.java
- universe/src/main/java/org/corfudb/universe/universe/node/server/corfu/CorfuServer.java
universe framework - Cassandra deployment fixes
> universe framework - cassandra deployment fixes

- tests/src/test/java/org/corfudb/test/AbstractCorfuUniverseTest.java
- tests/src/test/java/org/corfudb/test/docker/OneNodeDownDockerTest.java
- universe/src/main/java/org/corfudb/universe/api/universe/AbstractUniverse.java
- universe/src/main/java/org/corfudb/universe/api/universe/group/GroupParams.java
- universe/src/main/java/org/corfudb/universe/api/universe/group/cluster/Cluster.java
- universe/src/main/java/org/corfudb/universe/api/universe/node/CommonNodeParams.java
- universe/src/main/java/org/corfudb/universe/api/universe/node/Node.java
- universe/src/main/java/org/corfudb/universe/infrastructure/docker/universe/DockerUniverse.java
- universe/src/main/java/org/corfudb/universe/infrastructure/docker/universe/group/cluster/DockerMangleCluster.java
- universe/src/main/java/org/corfudb/universe/infrastructure/docker/universe/node/server/DockerNode.java
- universe/src/main/java/org/corfudb/universe/infrastructure/docker/universe/node/server/mangle/DockerMangleServer.java
- universe/src/main/java/org/corfudb/universe/scenario/fixture/FixtureUtil.java
- universe/src/main/java/org/corfudb/universe/scenario/fixture/Fixtures.java
- universe/src/main/java/org/corfudb/universe/universe/group/cluster/corfu/CorfuClusterParams.java
- universe/src/main/java/org/corfudb/universe/universe/node/server/mangle/MangleServerParams.java
- universe/src/test/java/org/corfudb/universe/group/CorfuClusterParamsTest.java
- universe/src/test/java/org/corfudb/universe/universe/node/server/CorfuServerParamsTest.java
universe framework - bring mangle
> universe framework - bring mangle

- tests/build.gradle.kts
- tests/src/main/java/org/corfudb/universe/test/UniverseConfigurator.java
- universe/docker/Dockerfile
- universe/docker/docker-entrypoint.sh
- universe/src/main/java/org/corfudb/universe/scenario/fixture/FixtureUtil.java
- universe/src/main/java/org/corfudb/universe/scenario/fixture/Fixtures.java
Bring corfu-docker-ssh: access to corfu node (docker) via ssh
> Bring corfu-docker-ssh: access to corfu node (docker) via ssh

- universe/src/main/java/org/corfudb/universe/infrastructure/docker/universe/node/server/corfu/DockerCorfuServer.java
- universe/src/main/java/org/corfudb/universe/infrastructure/process/universe/node/server/ProcessCorfuServer.java
- universe/src/main/java/org/corfudb/universe/infrastructure/vm/universe/node/server/VmCorfuServer.java
- universe/src/main/java/org/corfudb/universe/universe/node/server/corfu/CorfuServer.java
Remove not used "disconnect()" method
> Remove not used "disconnect()" method

- .github/workflows/publish-universe-artifacts.yml
- .github/workflows/pull_request_universe.yml
- .gitignore
- gradle/publishing.gradle.kts
- gradle/spotbugs.gradle
- universe/universe-core/build.gradle.kts
- universe/universe-infrastructure/build.gradle.kts
Publishing universe framework artifacts
> Publishing universe framework artifacts

- benchmarks/build.gradle.kts
- tests/build.gradle.kts
- tests/src/test/java/org/corfudb/test/AbstractCorfuUniverseTest.java
Universe framework - fix dependencies
> Universe framework - fix dependencies

- .github/workflows/publish-cloud.yml
- .github/workflows/publish-universe-artifacts.yml
- .github/workflows/pull_request_benchmarks.yml
- .github/workflows/pull_request_universe.yml
- .github/workflows/run_benchmarks.yml
- benchmarks/src/jmh/java/org/corfudb/benchmarks/runtime/collections/helper/CorfuTableBenchmarkHelper.java
- benchmarks/src/jmh/java/org/corfudb/benchmarks/runtime/collections/state/EhCacheState.java
- benchmarks/src/jmh/java/org/corfudb/benchmarks/runtime/collections/state/HashMapState.java
- benchmarks/src/jmh/java/org/corfudb/benchmarks/runtime/collections/state/RocksDbState.java
- benchmarks/src/main/java/org/corfudb/benchmarks/runtime/collections/experiment/ehcache/EhCacheMap.java
- config/spotbugs/excludeFilter.xml
- gradle/spotbugs.gradle
Github Actions: workflow optimizations and fixes
> Github Actions: workflow optimizations and fixes

- benchmarks/src/jmh/java/org/corfudb/benchmarks/cluster/ClusterBenchmark.java
- benchmarks/src/jmh/java/org/corfudb/benchmarks/runtime/collections/state/EhCacheState.java
- benchmarks/src/jmh/java/org/corfudb/benchmarks/runtime/collections/state/HashMapState.java
- benchmarks/src/jmh/java/org/corfudb/benchmarks/runtime/collections/state/RocksDbState.java
Benchmark: load generation relaxation
> Benchmark: load generation relaxation

- cloud/infrastructure/filebeat/filebeat/filebeat.yml
- cloud/infrastructure/logstash/logstash/configuration/pipeline/corfu-jvm.conf
> Logstash: fix GC parsing

- cloud/infrastructure/filebeat/filebeat/filebeat.yml
Logstash fix GC parsing: fix filebeat
> Logstash fix GC parsing: fix filebeat

- cloud/infrastructure/filebeat/filebeat/filebeat.yml
- cloud/infrastructure/logstash/logstash/manager/pipeline/logstash.conf
> Beats input codec tag

- cloud/infrastructure/logstash/logstash/configuration/pipeline/corfu-jvm.conf
> Logstash fix multiline filter

- cloud/infrastructure/logstash/logstash/configuration/pipeline/corfu-jvm.conf
Logstash "remove_filed" on if the operation was successful
> Logstash "remove_filed" on if the operation was successful

- cloud/infrastructure/kibana/dashboard/corfu-dashboard/jvm-gc-cluster-dashboard.json
Kibana dashboard: jvm-gc-cluster-dashboard fix references
> Kibana dashboard: jvm-gc-cluster-dashboard fix references

- cloud/infrastructure/kibana/dashboard/corfu-dashboard/jvm-gc-cluster-dashboard.json
Kibana dashboard: jvm-gc-cluster-dashboard add full gc cycles
> Kibana dashboard: jvm-gc-cluster-dashboard add full gc cycles

- gradle/dependencies.gradle
- tests/src/main/resources/universe-tests.properties
- universe/universe-core/src/main/java/org/corfudb/universe/scenario/fixture/UniverseFixture.java
- universe/universe-core/src/main/java/org/corfudb/universe/universe/node/server/corfu/LongevityAppParams.java
- universe/universe-infrastructure/src/main/java/org/corfudb/universe/infrastructure/docker/universe/group/cluster/ExternalDockerClusters.java
Universe framework: corfu longevity app improvements
> Universe framework: corfu longevity app improvements

- .gitignore
- tests/src/test/java/org/corfudb/test/AbstractCorfuUniverseTest.java
- tests/src/test/java/org/corfudb/test/TestGroups.java
- tests/src/test/java/org/corfudb/test/docker/infrastructure/LongevityTest.java
- universe/universe-core/src/main/java/org/corfudb/universe/api/universe/node/ApplicationServer.java
- universe/universe-core/src/main/java/org/corfudb/universe/infrastructure/docker/DockerManager.java
- universe/universe-core/src/main/java/org/corfudb/universe/infrastructure/docker/universe/node/server/DockerNode.java
- universe/universe-core/src/main/java/org/corfudb/universe/infrastructure/process/universe/node/server/ProcessCorfuServer.java
- universe/universe-core/src/main/java/org/corfudb/universe/infrastructure/vm/universe/node/server/VmCorfuServer.java
Implement Corfu longevity test in corfu universe
> Corfu longevity test

- benchmarks/build.gradle.kts
- cloud/build.gradle.kts
- gradle/idea-project.gradle.kts
- tests/Dockerfile
- tests/build.gradle.kts
- tests/settings.gradle.kts
- universe/build.gradle.kts
> Dockerized universe tests

- universe/universe-core/src/main/java/org/corfudb/universe/api/universe/group/GroupParams.java
- universe/universe-core/src/main/java/org/corfudb/universe/api/universe/group/cluster/Cluster.java
- universe/universe-core/src/main/java/org/corfudb/universe/infrastructure/docker/universe/group/cluster/DockerCorfuCluster.java
- universe/universe-core/src/main/java/org/corfudb/universe/infrastructure/docker/universe/group/cluster/DockerCorfuLongevityCluster.java
- universe/universe-core/src/main/java/org/corfudb/universe/infrastructure/process/universe/group/cluster/ProcessCorfuCluster.java
- universe/universe-core/src/main/java/org/corfudb/universe/infrastructure/vm/universe/group/cluster/VmCorfuCluster.java
- universe/universe-core/src/main/java/org/corfudb/universe/universe/group/cluster/corfu/AbstractCorfuCluster.java
- universe/universe-core/src/main/java/org/corfudb/universe/universe/group/cluster/corfu/CorfuClusterParams.java
- universe/universe-infrastructure/src/main/java/org/corfudb/universe/infrastructure/docker/universe/group/cluster/DockerCassandraCluster.java
- universe/universe-infrastructure/src/main/java/org/corfudb/universe/infrastructure/docker/universe/group/cluster/DockerMangleCluster.java
- universe/universe-infrastructure/src/main/java/org/corfudb/universe/infrastructure/docker/universe/group/cluster/DockerPrometheusCluster.java
Universe framework: make bootstrap step configurable
> Universe framework: make bootstrap step configurable

- universe/universe-core/src/main/java/org/corfudb/universe/api/universe/group/cluster/AbstractCluster.java
Universe: fix method "add server"
> Universe: fix method "add server"

- universe/universe-core/src/main/java/org/corfudb/universe/api/UniverseManager.java
- universe/universe-core/src/main/java/org/corfudb/universe/infrastructure/vm/universe/ApplianceManager.java
- universe/universe-core/src/main/java/org/corfudb/universe/infrastructure/vm/universe/VmUniverse.java
- universe/universe-core/src/main/java/org/corfudb/universe/infrastructure/vm/universe/group/cluster/VmCorfuCluster.java
- universe/universe-core/src/main/java/org/corfudb/universe/infrastructure/vm/universe/node/server/VmCorfuServer.java
- universe/universe-core/src/main/java/org/corfudb/universe/universe/node/server/corfu/CorfuServerParams.java
> Fixed deployment issue on Vsphere Cluster

- tests/src/test/java/org/corfudb/test/AbstractCorfuUniverseTest.java
- tests/src/test/java/org/corfudb/test/docker/infrastructure/LongevityTest.java
Universe framework tests: customizable setup
> Universe framework tests: customizable setup

- injection-framework/Dockerfile
- injection-framework/build.sh
- injection-framework/correctness/__init__.py
- injection-framework/correctness/client_report.py
- injection-framework/correctness/correctness_report.py
- injection-framework/correctness/key_state.py
- injection-framework/correctness/liveness_operation.py
- injection-framework/correctness/operation.py
- injection-framework/correctness/operation_factory.py
- injection-framework/correctness/read_inconsistency.py
- injection-framework/correctness/read_operation.py
- injection-framework/correctness/rm_operation.py
- injection-framework/correctness/state.py
- injection-framework/correctness/tx_operation.py
- injection-framework/correctness/tx_read_operation.py
- injection-framework/correctness/tx_rm_operation.py
- injection-framework/correctness/tx_state.py
- injection-framework/correctness/tx_write_operation.py
- injection-framework/correctness/update_version_operation.py
- injection-framework/correctness/verify_correctness.py
- injection-framework/correctness/write_operation.py
- injection-framework/requirements.txt
- injection-framework/utils/test_status.py
- injection-framework/utils/utils.py
- injection-framework/verification.py
- tests/src/test/java/org/corfudb/test/docker/infrastructure/LongevityTest.java
Injection framework: verification logic
> Injection framework: verification logic

- tests/src/test/java/org/corfudb/test/docker/infrastructure/LongevityTest.java
- tests/src/test/java/org/corfudb/test/failure/NodeFailure.java
- tests/src/test/java/org/corfudb/test/spec/OneNodeDownSpec.java
Longevity test: bring failures
> Longevity test: bring failures

- injection-framework/correctness/verify_correctness.py
Injection framework: print invalid log string
> Injection framework: print invalid log string

- tests/build.gradle.kts
Injection framework: gradle create "correctness log distribution" task
> Injection framework: gradle create "correctness log distribution" task

- gradle/corfu.gradle
Add gradle task: setCorfuServerVersion
> Add gradle task: setCorfuServerVersion

- .github/workflows/run-corfu-cloud-deployment.yml
- cloud/infrastructure/corfu/readme.md
Github actions: helm deployment and cloud run
> Github actions: helm deployment and cloud run

- .github/workflows/run-corfu-cloud-deployment.yml
> Cloud deployment testing

- cloud/corfu/corfu/config/logback.prod.xml
- cloud/corfu/corfu/java_opts/default
- cloud/corfu/corfu/templates/configmap.yaml
- cloud/corfu/corfu/templates/layoutconfigmap.yaml
- cloud/corfu/corfu/templates/statefulset.yaml
- cloud/corfu/corfu/values.yaml
> More corfu configurations

- cloud/corfu/corfu/config/compactor-logback.prod.xml
- cloud/corfu/corfu/config/corfu-compactor-config.yml
- cloud/corfu/corfu/config/logback.prod.xml
Modify logback files to add new loggers for compactor server side and client side logs
> Adding separate log files for compactor server and client paths

- universe/universe-core/build.gradle.kts
- universe/universe-infrastructure/build.gradle.kts
> Get rid of jfrog plugins

- tests/src/main/java/org/corfudb/universe/test/util/ScenarioUtils.java
After Corfu Disk 2.0 merge in CorfuDB master
update the CorfuTable usage to ICorfuTable.
> Fix ScenarioUtils ICorfuTable

- benchmarks/src/jmh/java/org/corfudb/benchmarks/cluster/ClusterBenchmark.java
- benchmarks/src/jmh/java/org/corfudb/benchmarks/runtime/collections/helper/CorfuTableBenchmarkHelper.java
- benchmarks/src/jmh/java/org/corfudb/benchmarks/runtime/collections/state/EhCacheState.java
- benchmarks/src/jmh/java/org/corfudb/benchmarks/runtime/collections/state/HashMapState.java
- benchmarks/src/jmh/java/org/corfudb/benchmarks/runtime/collections/state/RocksDbState.java
- cloud/corfu/corfu-client-example/src/main/java/org.corfudb.cloud.runtime.example/Main.java
- tests/src/test/java/org/corfudb/test/spec/CheckPointTrimSpec.java
> Fix CorfuTable usages to ICorfuTable

- tests/src/test/java/org/corfudb/test/spec/CheckPointTrimSpec.java
> Fix CorfuTable usages to ICorfuTable: addOpenOption

- cloud/corfu/corfu/templates/_helpers.tpl
Add imageSpec into corfu helm template
> Add imageSpec into corfu helm template

- cloud/corfu/corfu/values.yaml
cert manager, migrate to cluster issuer
> cert manager, migrate to cluster issuer

- cloud/corfu/corfu/values.yaml
Reverts CorfuDB/corfudb-cloud#253
> Revert "cert manager, migrate to cluster issuer"

- cloud/corfu/corfu/templates/job.yaml
cloud deployment: fix job.yaml
> cloud deployment: fix job.yaml

- cloud/corfu/corfu/values.yaml
* Adds back logPersistence helm values needed post revert.
> Add log persistence value
